version: "3"

services:

  app:

    build: .docker/app/
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .docker/app/default.conf:/etc/apache2/sites-available/000-default.conf
      - .docker/app/php.ini:/usr/local/etc/php/php.ini

volumes:

  data:
